/*1628075512000*/
var cookieName="ACCEPTS_COOKIES";var cookieMessageId="cookie-warning";function checkAnalyticsCookie(){if(jQuery.cookie(cookieName)!="false")if(jQuery.cookie(cookieName)==="true"){addGoogleAnalytics();loadIFrames();setAnalytics()}else if(jQuery("#"+cookieMessageId).length>0)showCookieWarning();else{addGoogleAnalytics();loadIFrames();setAnalytics()}}
function showCookieWarning(){changeCookieWarningButtonValue();jQuery("#"+cookieMessageId).slideDown();jQuery("body").bind("click",function(e){if(jQuery("#interstitial-modal").length==0)if(e.target.id!="closemodal"&&e.target.id!="closethick")if(!(jQuery(e.target).parents("#"+cookieMessageId+", .grifols-popup").length>0||jQuery(e.target).attr("id")==cookieMessageId))acceptCookiePolicy()});window.location.hash=""}
function changeCookieWarningButtonValue(){var currentLiteral=$('#cookie-warning .btnHolder input[type\x3d"button"]').val();var newLiteral=Liferay.closeString;if(typeof currentLiteral!="undefined"&&typeof newLiteral!="undefined")if(currentLiteral.toUpperCase()!=newLiteral.toUpperCase())$('#cookie-warning .btnHolder input[type\x3d"button"]').val(newLiteral.toUpperCase())}
function acceptCookiePolicy(){jQuery("body").unbind("click");jQuery.cookie(cookieName,"true",{expires:365,path:"/"});addGoogleAnalytics();loadIFrames();setAnalytics();jQuery("#"+cookieMessageId).slideUp()}function rejectCookiePolicy(){jQuery("body").unbind("click");jQuery.cookie(cookieName,"false",{expires:365,path:"/"});jQuery("#"+cookieMessageId).slideUp()}function addGoogleAnalytics(){Grifols.common.analytics.enable()}
function pushKeyword(){var keyword=jQuery('input[name$\x3d"keywords"]').val();if(!(keyword==="")){var _url=addParameterToURL("q\x3d"+keyword,document.location.pathname);sendSearchKeyword(keyword)}}function addParameterToURL(param,url){_url=url;_url+=(_url.split("?")[1]?"\x26":"?")+param;return _url}function blockIFrames(){jQuery("iframe").each(function(){jQuery(this).attr("src1",jQuery(this).attr("src"));jQuery(this).attr("src","about:blank")})}
function loadIFrames(){jQuery("iframe").each(function(){if(typeof jQuery(this).attr("src1")!="undefined"&&jQuery(this).attr("src1")!=""){jQuery(this).attr("src",jQuery(this).attr("src1"));jQuery(this).removeAttr("src1")}})}if(typeof jQuery!="undefined"){$(window).on("load",function(){if($("#cookie-intro").length>0)Grifols.BCS.cookies.checkCookiesManagement();else checkAnalyticsCookie()});jQuery(document).ready(function(){if(jQuery("#"+cookieMessageId).length>0)if(jQuery.cookie(cookieName)!="true")blockIFrames()})}
var analyticsDebug=false;function sendAnalyticsEvent(section,event,object){if(typeof ga!="undefined")ga("send","event",section,event,object)}function sendSearchKeyword(keyword){if(keyword==="")keyword="(Empty)";sendAnalyticsEvent("Search","click",keyword)}var submitted=false;
function sendSubmitEvent(formName){submitted=true;$(".aui-field-input-choice").parent("span").find("input[type\x3dhidden]").each(function(){if($(this).val()=="true")if($(this).parents(".checkbox-list").length>0){var parentItem=$(this).parents(".item");if(parentItem.length>0)sendAnalyticsEvent("Checkbox",formName,parentItem.find(".checkbox-right .description").text())}});sendAnalyticsEvent("Form","submit",formName)}
function addLeavePageEvent(formName){window.onbeforeunload=function(e){if(!submitted){var inputList=[];var isContactForm=true;var fieldList=[];if($(".body-fieldset .col-resp-12").length>0)$(".body-fieldset .col-resp-12").each(function(){inputList.push($(this))});if($(".field-row").length>0){isContactForm=false;$(".field-row").each(function(){inputList.push($(this))})}else $(".aui-field").each(function(){inputList.push($(this))});for(var index=0;index<inputList.length;index++){var thisInput=$(inputList[index]);
var thisField=thisInput.find("input[type\x3d'text']");if(thisField.length==0)thisField=thisInput.find("textarea");if(thisField.length==0)thisField=thisInput.find("select");if(thisField.length>0){var fieldLabel;if(isContactForm)fieldLabel=$.trim(thisInput.find("label.aui-field-label-inline-label").text());else fieldLabel=$.trim(thisInput.find(".field-label h4").text());if(fieldLabel==""&&thisInput.find("label").length>0)fieldLabel=$.trim(thisInput.find("label").text());var fieldStatus;if(thisInput.hasClass("ocu"))fieldStatus=
"H";else if(thisField.val()!=""&&thisField.val()!=thisField.attr("placeholder"))if(thisField.hasClass("aui-form-validator-error"))fieldStatus="E";else fieldStatus="X";else fieldStatus=" ";if(fieldLabel.length>0)fieldList.push("["+fieldStatus+"] "+fieldLabel)}}if(analyticsDebug)console.log("Fields to send -\x3e "+fieldList);sendAnalyticsEvent("Not submitted form",formName,fieldList.toString())}}}
function addOnClick(objects,section,eventName){var eventsAdded=0;if(objects.length>0){objects.each(function(){if($(this).attr("onClick")==undefined){var eventText=$(this).attr("alt");if(eventText==undefined)eventText=$(this).attr("title");if(eventText==undefined&&$(this).attr("href")!=undefined&&$(this).attr("href").indexOf("/documents/")!=-1){eventText=$(this).attr("href").substring($(this).attr("href").indexOf("/documents/"));eventText=eventText.split("/")[4]}if(eventText==undefined)eventText=$(this).attr("href");
if(eventText!=undefined){if($(this).children("img").length>0)eventText="Image link: "+eventText;eventText=eventText.replace(/'/g,"\\x27");$(this).attr("onclick","sendAnalyticsEvent('"+section+"','"+eventName+"','"+eventText+"');");$(this).attr("oncontextmenu","sendAnalyticsEvent('"+section+"','right-click','"+eventText+"');");eventsAdded++}}});if(analyticsDebug)console.log(eventsAdded+" "+eventName+" events added for section -\x3e "+section)}}
function fixVirtualhostLinks(){if(typeof siteUrl!="undefined")if(location.href.indexOf("/web"+siteUrl+"/")<0&&location.href.indexOf("/group"+siteUrl+"/"))$("#wrapper a, #footer a").each(function(){if($(this).attr("href")!=undefined&&($(this).attr("href").indexOf("/web"+siteUrl+"/")>=0||$(this).attr("href").endsWith("/web"+siteUrl)))$(this).attr("href",$(this).attr("href").replace("/web"+siteUrl,""))})}
function fixStagingLinks(){if(typeof siteUrl!="undefined")if(location.href.indexOf("/web"+siteUrl+"/")>=0||location.href.endsWith("/web"+siteUrl))$("#wrapper a, #footer a").each(function(){var thisHref=$(this).attr("href");if(typeof thisHref!="undefined")if(thisHref.indexOf("/")==0&&thisHref.indexOf("/documents/")<0&&thisHref.indexOf("/web"+siteUrl)<0&&thisHref.indexOf("/group/")<0&&thisHref.indexOf("/c/")<0)if(thisHref.charAt(3)=="/")$(this).attr("href",thisHref.substring(0,3)+"/web"+siteUrl+thisHref.substring(3));
else $(this).attr("href","/web"+siteUrl+thisHref)})}function rewriteInternalLinks(){}
function setBCSTagging(){rewriteInternalLinks();addOnClick($("#grifols-link").find("a"),"Header","click");addOnClick($("#pheader .pheader-menu").find("a"),"Header","click");addOnClick($("#pheader .custom-pages").find("a"),"Header","click");addOnClick($("#pheader .contactus").find("a"),"Header","click");addOnClick($(".important-safety-link").find("a"),"ISI","click");addOnClick($("#header-menu .lvl1\x3ea"),"Top Nav","click");addOnClick($("#header-menu .lvl2").find("a"),"Sub Nav","click");addOnClick($("a[href^\x3d'tel:']"),
"Telephone Number","Click-to-call");addOnClick($("a[href^\x3d'mailto:']"),"Mailto Link","click");addOnClick($("#footer").find("a"),"Footer","click");addOnClick($("a[href$\x3d'forgot_password']"),"Change password link","click");addOnClick($("a[href*\x3d'/documents/']"),"Document","download");addOnClick($("a[href^\x3d'/']"),"Internal Link","click");addOnClick($("a[href^\x3d'"+location.protocol+"//"+location.hostname+"'"),"Internal Link","click");addOnClick($("a[href^\x3d'http']"),"Outgoing Link","click");
setVideoEvents();setScrollEvents()}function updateQueryStringParameter(uri,key,value){var re=new RegExp("([?\x26])"+key+"\x3d.*?(\x26|$)","i");var separator=uri.indexOf("?")!==-1?"\x26":"?";if(uri.match(re))return uri.replace(re,"$1"+key+"\x3d"+value+"$2");else return uri+separator+key+"\x3d"+value}
function createChangeLanguageStrutsActionURL(plid,action){var t=new Date;var url=action;url+="?"+"plid\x3d"+plid;url+="\x26"+"p_auth\x3d"+Liferay.authToken;var redirect=location.pathname+location.search;url+="\x26"+"currentLanguage\x3d"+Liferay.ThemeDisplay.getLanguageId();url+="\x26"+"redirect\x3d"+encodeURIComponent(redirect);return url}
if(typeof $!="undefined")$(document).ready(function(){AUI().ready("liferay-portlet-url",function(A){var url=createChangeLanguageStrutsActionURL(themeDisplay.getPlid(),"/c/portal/change_language");var currentLanguageId=Liferay.ThemeDisplay.getLanguageId();$("#languageselect option").each(function(){var value=$(this).val();var languageIdParam=getUrlParameter(value,"languageId");if(languageIdParam!=null||languageIdParam!="undefined")languageIdParam=languageIdParam.substring(0,2);if(value!=""&&value.indexOf("/")==
0)if(typeof languageIdParam=="undefined"||currentLanguageId==languageIdParam){var languageCode=value.substring(1,3);var languageId="";var locale=Liferay.availableLocales[languageCode];if(typeof locale!="undefined")languageId=locale.languageId;var localeUrl=url+"\x26languageId\x3d"+languageId;if(currentLanguageId==languageId)if(languageIdParam==null||languageIdParam=="undefined"||currentLanguageId==languageIdParam)localeUrl="javascript:void(0)";$(this).val(localeUrl)}});$("li.languageli .languagelist div a").each(function(){var value=
$(this).attr("href");var languageIdParam=getUrlParameter(value,"languageId");if(languageIdParam!=null||languageIdParam!="undefined")languageIdParam=languageIdParam.substring(0,2);if(value!=""&&value.indexOf("/")==0)if(typeof languageIdParam=="undefined"||currentLanguageId==languageIdParam){var languageCode=value.substring(1,3);var languageId="";var locale=Liferay.availableLocales[languageCode];if(typeof locale!="undefined")languageId=locale.languageId;var localeUrl=url+"\x26languageId\x3d"+languageId;
if(currentLanguageId==languageId)localeUrl="javascript:void(0)";$(this).attr("href",localeUrl)}});$("ul.menu-movil li#menu-more ul li a").each(function(){var value=$(this).attr("href");if(value!=""&&value.indexOf("/")==0)if(typeof languageIdParam=="undefined"||currentLanguageId==languageIdParam){var languageCode=value.substring(1,3);var languageId="";var locale=Liferay.availableLocales[languageCode];if(typeof locale!="undefined"){languageId=locale.languageId;var languageNodeName=$(this).text();var languageRealName=
Liferay.Language.get(locale.languageId);if(languageNodeName==languageRealName){var localeUrl=url+"\x26languageId\x3d"+languageId;if(currentLanguageId==languageId)localeUrl="javascript:void(0)";$(this).attr("href",localeUrl)}}}})})});var BCTagging={};BCTagging.debug=false;BCTagging.players=[];BCTagging.videos=[];BCTagging.progress={};BCTagging.progressPc={};BCTagging.lastPositionSent={};
BCTagging.onTemplateLoad=function(experienceID){if(BCTagging.debug)console.log("ontemplateload");BCTagging.player=brightcove.api.getExperience(experienceID);BCTagging.modVP=BCTagging.player.getModule(brightcove.api.modules.APIModules.VIDEO_PLAYER);BCTagging.players.push(experienceID)};
BCTagging.onTemplateReady=function(event){if(BCTagging.debug)console.log("templateready");BCTagging.modVP.addEventListener(brightcove.api.events.MediaEvent.BEGIN,function(event){BCTagging.startVideo(event)});BCTagging.modVP.addEventListener(brightcove.api.events.MediaEvent.PROGRESS,function(event){BCTagging.progressVideo(event)});BCTagging.modVP.addEventListener(brightcove.api.events.MediaEvent.PLAY,function(event){BCTagging.playVideo(event)});BCTagging.modVP.addEventListener(brightcove.api.events.MediaEvent.COMPLETE,
function(event){BCTagging.finishVideo(event)})};
BCTagging.startVideo=function(event){if(BCTagging.debug)console.log("Play -\x3e "+event.media.displayName);sendVideoAnalyticsEvent("Play",event.media.displayName);var found=false;for(var i=0;i<BCTagging.videos.length;i++)if(BCTagging.videos[i]==event.media.displayName){found=true;break}if(!found)BCTagging.videos.push(event.media.displayName);window.onbeforeunload=function(e){for(var i=0;i<BCTagging.videos.length;i++){var videoTitle=BCTagging.videos[i];var lastTimeStamp=parseInt(BCTagging.progress[videoTitle]);
var minutes=Math.round(Math.floor(lastTimeStamp/60));var seconds=lastTimeStamp%60;var timestamp=("0"+minutes).slice(-2)+":"+("0"+seconds).slice(-2);if(BCTagging.debug)console.log("Leave page -\x3e "+BCTagging.progressPc[videoTitle]+"%, "+timestamp+" -\x3e "+videoTitle);sendVideoAnalyticsEvent("Leave page -\x3e "+BCTagging.progressPc[videoTitle]+"%, "+timestamp,videoTitle)}}};
BCTagging.progressVideo=function(event){var partThreshold=25;if(typeof BCTagging.lastPositionSent[event.media.displayName]==="undefined")BCTagging.lastPositionSent[event.media.displayName]=0;BCTagging.progress[event.media.displayName]=event.position;BCTagging.progressPc[event.media.displayName]=parseInt(BCTagging.progress[event.media.displayName]/event.duration*100);var currentPosition=parseInt(BCTagging.progressPc[event.media.displayName]/partThreshold);if(currentPosition!=BCTagging.lastPositionSent[event.media.displayName]){if(BCTagging.debug)console.log(currentPosition*
partThreshold+"% of video reached -\x3e "+event.media.displayName);sendVideoAnalyticsEvent("Progress -\x3e "+currentPosition*partThreshold+"%",event.media.displayName);BCTagging.lastPositionSent[event.media.displayName]=currentPosition}};BCTagging.finishVideo=function(event){if(BCTagging.debug)console.log("Video finished -\x3e "+event.media.displayName);sendVideoAnalyticsEvent("Progress -\x3e 100%",event.media.displayName)};
BCTagging.playVideo=function(event){for(var i=0;i<BCTagging.players.length;i++)if(players[i]!=id){var player=brightcove.api.getExperience(BCTagging.players[i]);var videoPlayer=player.getModule(brightcove.api.modules.APIModules.VIDEO_PLAYER);videoPlayer.pause(true)}};function sendVideoAnalyticsEvent(eventText,videoTitle){sendAnalyticsEvent("Video",eventText,videoTitle)}function setAnalytics(){Grifols.common.analytics.setAnalytics()}var videoTagging={};videoTagging.videos=[];videoTagging.progress={};
videoTagging.progressPc={};videoTagging.lastPositionSent={};var nombreVideos="";
function setVideoEvents(){$("video").each(function(e){var video=this;var videoId=$(video).parent().attr("id");videojs(videoId).on("play",function(){var myPlayer=this;playHandler(myPlayer)});videojs(videoId).on("timeupdate",function(){var myPlayer=this;timeupdateHandler(myPlayer)});videojs(videoId).on("ended",function(){var myPlayer=this;sendVideoAnalyticsEvent("Progress -\x3e 100%",myPlayer.mediainfo.name);videoTagging.progressPc[myPlayer.mediainfo.name]=100})});function playHandler(myPlayer){if(typeof videoTagging.lastPositionSent[myPlayer.mediainfo.name]===
"undefined")videoTagging.lastPositionSent[myPlayer.mediainfo.name]=0;if(typeof videoTagging.progress[myPlayer.mediainfo.name]==="undefined")videoTagging.progress[myPlayer.mediainfo.name]=0;if(typeof videoTagging.progressPc[myPlayer.mediainfo.name]==="undefined")videoTagging.progressPc[myPlayer.mediainfo.name]=0;var found=false;for(var i=0;i<videoTagging.videos.length;i++)if(videoTagging.videos[i]==myPlayer.mediainfo.name){found=true;break}if(!found){videoTagging.videos.push(myPlayer.mediainfo.name);
if(BCTagging.debug)console.log("Play "+myPlayer.mediainfo.name);sendVideoAnalyticsEvent("Play ",myPlayer.mediainfo.name);window.onbeforeunload=function(e){for(var i=0;i<videoTagging.videos.length;i++){var videoTitle=videoTagging.videos[i];if(videoTitle!="undefined"){var lastTimeStamp=parseInt(videoTagging.progress[videoTitle]);var minutes=Math.round(Math.floor(lastTimeStamp/60));var seconds=lastTimeStamp%60;var timestamp=("0"+minutes).slice(-2)+":"+("0"+seconds).slice(-2);if(BCTagging.debug)console.log("Leave page -\x3e "+
videoTagging.progressPc[videoTitle]+"%, "+timestamp+" -\x3e "+videoTitle);sendVideoAnalyticsEvent("Leave page -\x3e "+videoTagging.progressPc[videoTitle]+"%, "+timestamp,videoTitle)}}}}}function timeupdateHandler(myPlayer){var partThreshold=25;if(typeof videoTagging.lastPositionSent[myPlayer.mediainfo.name]==="undefined")videoTagging.lastPositionSent[myPlayer.mediainfo.name]=0;if(typeof videoTagging.progress[myPlayer.mediainfo.name]==="undefined")videoTagging.progress[myPlayer.mediainfo.name]=0;else videoTagging.progress[myPlayer.mediainfo.name]=
myPlayer.currentTime();if(typeof videoTagging.progressPc[myPlayer.mediainfo.name]==="undefined"||isNaN(myPlayer.mediainfo.duration))videoTagging.progressPc[myPlayer.mediainfo.name]=0;else videoTagging.progressPc[myPlayer.mediainfo.name]=Math.ceil(parseInt(videoTagging.progress[myPlayer.mediainfo.name]/myPlayer.mediainfo.duration*100));var currentPosition=parseInt(videoTagging.progressPc[myPlayer.mediainfo.name]/partThreshold);if(currentPosition!=videoTagging.lastPositionSent[myPlayer.mediainfo.name]){if(BCTagging.debug)console.log(currentPosition*
partThreshold+"% of video reached -\x3e "+myPlayer.mediainfo.name);sendVideoAnalyticsEvent("Progress -\x3e "+currentPosition*partThreshold+"%",myPlayer.mediainfo.name);videoTagging.lastPositionSent[myPlayer.mediainfo.name]=currentPosition}}}var scrollArray=[];var scrolledArray=[];var scroll=$(window).scrollTop()+$(window).height();
function setScrollEvents(){var counter=0;$(".bcs-scroll").each(function(){scrollArray[counter]=$(this).attr("id");scrolledArray[counter]=scroll>$(this).offset().top;counter++});if(scrollArray.length>0)$(window).scroll(function(){var scroll=$(window).scrollTop()+$(window).height();for(var i=0;i<scrollArray.length;i++)if(scroll>$("#"+scrollArray[i]).offset().top&&!scrolledArray[i]){if($("#"+scrollArray[i]).data("noninteraction")===true){if(typeof ga!="undefined")ga("send","event","Page Scroll","Scroll "+
$("#"+scrollArray[i]).data("scrollvalue")+"%",$("title").text(),{nonInteraction:true})}else sendAnalyticsEvent("Page Scroll","Scroll "+$("#"+scrollArray[i]).data("scrollvalue")+"%",$("title").text());scrolledArray[i]=true}for(var i=0;i<scrollArray.length;i++)if(scrolledArray[i]&&scroll<$("#"+scrollArray[i]).offset().top)scrolledArray[i]=false})}if(typeof Grifols==="undefined")var Grifols={};if(typeof Grifols.BCS==="undefined")Grifols.BCS={};
if(typeof Grifols.BCS.cookies==="undefined")Grifols.BCS.cookies={};Grifols.BCS.cookies.cookieConsentName="COOKIES_CONSENT";
Grifols.BCS.cookies.checkCookiesManagement=function(){if(typeof jQuery.cookie(Grifols.BCS.cookies.cookieConsentName)==="undefined"){blockIFrames();if(typeof Grifols.BCS.cookies.policyPage!="undefined"&&location.href.indexOf(Grifols.BCS.cookies.policyPage)<0)Grifols.BCS.cookies.openCookiesSettings()}else{var cookieString=jQuery.cookie(Grifols.BCS.cookies.cookieConsentName);try{var decodedCookie=atob(cookieString);var cookieJSON=JSON.parse(decodedCookie);var consentDateInt=parseInt(cookieJSON.cookiesconsentdate);
var needToAcceptCookiesAgain=false;if(typeof essentialsCookiesContext!=="undefined"){var essentialsDateInt=parseInt(essentialsCookiesContext.cookie_last_modified_date);if(consentDateInt<=essentialsDateInt)needToAcceptCookiesAgain=true}if(typeof analyticsCookiesContext!=="undefined"){var analyticsDateInt=parseInt(analyticsCookiesContext.cookie_last_modified_date);if(consentDateInt<=analyticsDateInt)needToAcceptCookiesAgain=true}if(typeof marketingCookiesContext!=="undefined"){var analyticsDateInt=
parseInt(marketingCookiesContext.cookie_last_modified_date);if(consentDateInt<=analyticsDateInt)needToAcceptCookiesAgain=true}if(needToAcceptCookiesAgain){if(typeof Grifols.BCS.cookies.policyPage!="undefined"&&location.href.indexOf(Grifols.BCS.cookies.policyPage)<0)Grifols.BCS.cookies.openCookiesSettings()}else{if(cookieJSON.preferences.analytic=="true"){addGoogleAnalytics();loadIFrames();setAnalytics()}else Grifols.BCS.cookies.removeAnalyticsCookies();if(typeof cookieJSON.preferences.marketing!=
"undefined")if(cookieJSON.preferences.marketing=="true")Grifols.BCS.cookies.addMarketingCookies();else Grifols.BCS.cookies.removeMarketingCookies()}}catch(e){$.removeCookie(Grifols.BCS.cookies.cookieConsentName,{path:"/"})}}};
Grifols.BCS.cookies.validateCreatedCookiesAreDefined=function(){var currentCookies="";var unknownCookies="";$.each(document.cookie.split(/; */),function(){var splitCookie=this.split("\x3d");var cookieKey=splitCookie[0];var cookieValue=splitCookie[1];if(typeof cookieValue!="undefined"&&cookieValue!==null&&cookieValue!==""){var exists=false;var ignore=false;var legacy=false;if(typeof essentialsCookiesContext!=="undefined")for(var iter=0;iter<essentialsCookiesContext.cookie_names.length;iter++){var essentialCookieName=
essentialsCookiesContext.cookie_names[iter];if(essentialCookieName.indexOf("#")==essentialCookieName.length-1){essentialCookieName=essentialCookieName.substring(0,essentialCookieName.length-1);if(cookieKey.indexOf(essentialCookieName)==0)exists=true}else if(cookieKey===essentialCookieName)exists=true}if(typeof analyticsCookiesContext!=="undefined")for(var iter=0;iter<analyticsCookiesContext.cookie_names.length;iter++){var analyticsCookieName=analyticsCookiesContext.cookie_names[iter];if(analyticsCookieName.indexOf("#")==
analyticsCookieName.length-1){analyticsCookieName=analyticsCookieName.substring(0,analyticsCookieName.length-1);if(cookieKey.indexOf(analyticsCookieName)==0)exists=true}else if(cookieKey===analyticsCookieName)exists=true}if(typeof marketingCookiesContext!=="undefined")for(var iter=0;iter<marketingCookiesContext.cookie_names.length;iter++){var marketingCookieName=marketingCookiesContext.cookie_names[iter];if(marketingCookieName.indexOf("#")==marketingCookieName.length-1){marketingCookieName=marketingCookieName.substring(0,
marketingCookieName.length-1);if(cookieKey.indexOf(marketingCookieName)==0)exists=true}else if(cookieKey===marketingCookieName)exists=true}if(typeof ignoreCookiesContext!=="undefined")for(var iter=0;iter<ignoreCookiesContext.cookie_names.length;iter++){var ignoreCookieName=ignoreCookiesContext.cookie_names[iter];if(ignoreCookieName.indexOf("#")==ignoreCookieName.length-1){ignoreCookieName=ignoreCookieName.substring(0,ignoreCookieName.length-1);if(cookieKey.indexOf(ignoreCookieName)==0)ignore=true}else if(cookieKey===
ignoreCookieName)ignore=true}if(typeof legacyCookiesContext!=="undefined")for(var iter=0;iter<legacyCookiesContext.cookie_names.length;iter++){var legacyCookieName=legacyCookiesContext.cookie_names[iter];if(legacyCookieName.indexOf("#")==legacyCookieName.length-1){legacyCookieName=legacyCookieName.substring(0,legacyCookieName.length-1);if(cookieKey.indexOf(legacyCookieName)==0)legacy=true}else if(cookieKey===legacyCookieName)legacy=true}if(!ignore&&!legacy)if(!exists){if(unknownCookies==="")unknownCookies=
cookieKey;else unknownCookies=unknownCookies+","+cookieKey;Grifols.BCS.cookies.removeCookieNameGettingDomain(cookieKey)}else if(currentCookies==="")currentCookies=cookieKey;else currentCookies=currentCookies+","+cookieKey;if(legacy){Grifols.BCS.cookies.removeCookieNameGettingDomain(cookieKey);if(Grifols.BCS.cookies.getCookie(cookieKey)!==null)Grifols.BCS.cookies.removeCookieName(cookieKey)}}});$.ajax({async:false,type:"POST",data:{siteGroupId:parseInt(Liferay.ThemeDisplay.getScopeGroupId()),currentCookies:currentCookies,
unknownCookies:unknownCookies},url:"/c/portal/cookies/cookies_validation",dataType:"json",success:function(){}})};
Grifols.BCS.cookies.showCookieManagement=function(){if($("#cookie-intro-modal").length>0){$("#cookie-intro-modal").removeClass("modal-dialog-open");$("#cookie-intro-modal").addClass("modal-dialog-hidden")}var bodyContentHtml=AUI().one("#cookie-settings").html();if(typeof jQuery.cookie(Grifols.BCS.cookies.cookieConsentName)!="undefined"){var cookieString=jQuery.cookie(Grifols.BCS.cookies.cookieConsentName);var decodedCookie=atob(cookieString);var cookieJSON=JSON.parse(decodedCookie);if(cookieJSON.preferences.analytic==
"true")bodyContentHtml=bodyContentHtml.replace('\x3cinput id\x3d"analytic-preference"','\x3cinput id\x3d"analytic-preference" checked')}AUI().use("aui-modal",function(A){(new A.Modal({bodyContent:bodyContentHtml,id:"cookie-settings-modal",cssClass:"grifols-popup",centered:true,draggable:false,resizable:false,title:"",modal:true,constrain2view:true,destroyOnClose:true,zIndex:Liferay.zIndex.OVERLAY})).render()})};
Grifols.BCS.cookies.saveCookiesPreferences=function(preferences){var cookieJSON=JSON.parse(JSON.stringify(preferences));if(cookieJSON.analytic=="false")Grifols.BCS.cookies.removeAnalyticsCookies();if(typeof cookieJSON.marketing!="undefined"&&cookieJSON.marketing=="false")Grifols.BCS.cookies.removeMarketingCookies();Grifols.BCS.cookies.validateCreatedCookiesAreDefined();$.ajax({async:false,type:"POST",data:{preferences:preferences},url:"/c/portal/cookies/cookies_consent",dataType:"json",error:function(e){console.log("Error:");
console.log(e)},success:function(){location.reload()}})};Grifols.BCS.cookies.acceptAllCookies=function(cookieTypes){var jsonCookies='{"essential":"true"';if(typeof cookieTypes!="undefined"&&cookieTypes!=""){var types=cookieTypes.split(",");for(var i=0;i<types.length;i++)jsonCookies=jsonCookies+',"'+types[i]+'":"true"'}jsonCookies=jsonCookies+"}";Grifols.BCS.cookies.saveCookiesPreferences(jsonCookies)};
Grifols.BCS.cookies.refuseAllCookies=function(cookieTypes){var jsonCookies='{"essential":"true"';if(typeof cookieTypes!="undefined"&&cookieTypes!=""){var types=cookieTypes.split(",");for(var i=0;i<types.length;i++)jsonCookies=jsonCookies+',"'+types[i]+'":"false"'}jsonCookies=jsonCookies+"}";Grifols.BCS.cookies.saveCookiesPreferences(jsonCookies)};
Grifols.BCS.cookies.updateCookiePreferences=function(cookieTypes){var jsonCookies='{essential:"true"';if(typeof cookieTypes!="undefined"&&cookieTypes!=""){var types=cookieTypes.split(",");for(var i=0;i<types.length;i++)jsonCookies=jsonCookies+","+types[i]+':"'+$("#"+types[i]+"-preference").prop("checked")+'"'}jsonCookies=jsonCookies+"}";Grifols.BCS.cookies.saveCookiesPreferences(jsonCookies)};
Grifols.BCS.cookies.removeAnalyticsCookies=function(){if(typeof analyticsCookiesContext!="undefined"&&analyticsCookiesContext!=""){var domainCookie="";for(var iter=0;iter<analyticsCookiesContext.cookie_names.length;iter++)if(Grifols.BCS.cookies.getCookie(analyticsCookiesContext.cookie_names[iter])!==null)Grifols.BCS.cookies.removeCookieNameGettingDomain(analyticsCookiesContext.cookie_names[iter])}};Grifols.BCS.cookies.addMarketingCookies=function(){};Grifols.BCS.cookies.removeMarketingCookies=function(){};
Grifols.BCS.cookies.openCookiesSettings=function(){AUI().use("aui-modal",function(A){(new A.Modal({bodyContent:A.one("#cookie-intro").html(),id:"cookie-intro-modal",cssClass:"grifols-popup",centered:true,draggable:false,resizable:false,title:"",modal:true,constrain2view:true,destroyOnClose:true,zIndex:Liferay.zIndex.OVERLAY})).render();setTimeout(Grifols.BCS.cookies.initCompany(),500)})};
Grifols.BCS.cookies.removeCookieNameGettingDomain=function(cookieKey){var domainCookie="";if(Grifols.BCS.cookies.getCookie(cookieKey)!==null){var continueLoop=1;domainCookie=location.hostname;Grifols.BCS.cookies.removeCookieName(cookieKey,domainCookie);if(Grifols.BCS.cookies.getCookie(cookieKey)===null||domainCookie==="")continueLoop=0}};Grifols.BCS.cookies.removeCookieName=function(name){Grifols.BCS.cookies.removeCookieName(name,"")};
Grifols.BCS.cookies.removeCookieName=function(name,domainCookie){jQuery.removeCookie(name,{path:"/",domain:domainCookie})};Grifols.BCS.cookies.getCookie=function(name){if(typeof name!="undefined"&&name!==""){var nameValue=document.cookie.match("(^|;) ?"+name+"\x3d([^;]*)(;|$)");return nameValue?nameValue[2]:null}};
Grifols.BCS.cookies.createCookieName=function(name,value,expiry){var expires=new Date;expires.setTime(expires.getTime()+expiry*24*60*60*1E3);document.cookie=name+"\x3d"+value+";path\x3d/;expires\x3d"+expires.toUTCString()};
Grifols.BCS.cookies.initCompany=function(){$(".grifols-company").mouseenter(function(){Grifols.BCS.cookies.showCompany(false)});$(".grifols-company").mouseleave(function(){$(".grifols-company-detail:not(.open)").fadeOut()});$(".grifols-company").click(function(){Grifols.BCS.cookies.showCompany(true)});$(".grifols-company-detail .close").click(function(){$(".grifols-company-detail").removeClass("open");$(".grifols-company-detail").fadeOut()})};
Grifols.BCS.cookies.showCompany=function(isClick){var minMargin=26;var topPosition=$(".grifols-company").position().top+parseInt($(".grifols-company").css("line-height"))+5;var leftPosition=$(".grifols-company").position().left+$(".grifols-company").outerWidth()/2-$(".grifols-company-detail").outerWidth()/2;var pageStartLeft=minMargin;var pageStartRight=$("#cookie-intro-modal").outerWidth()-$(".grifols-company-detail").outerWidth()-minMargin;var arrowUpLeft=$(".grifols-company-detail").outerWidth()/
2-10;if(leftPosition<pageStartLeft){arrowUpLeft=arrowUpLeft+leftPosition-pageStartLeft;leftPosition=pageStartLeft}if(leftPosition>pageStartRight){arrowUpLeft=arrowUpLeft+leftPosition-pageStartRight;leftPosition=pageStartRight}$(".grifols-company-detail").css("top",topPosition+"px");$(".grifols-company-detail").css("left",leftPosition+"px");$(".grifols-company-detail").find(".arrow-up").css("left",arrowUpLeft+"px");$(".grifols-company-detail").fadeIn();if(isClick)$(".grifols-company-detail").addClass("open")};
function getUrlParameter(url,name){name=name.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]");var regex=new RegExp("[\\?\x26]"+name+"\x3d([^\x26#]*)");var results=regex.exec(url);return results===null?"":decodeURIComponent(results[1].replace(/\+/g," "))};